version: '2'
volumes:
  mysql-data-volume: {}
services:
  mysql:
    image: mariadb
    networks:
      - varapp
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: users_db
    volumes:
      - mysql-data-volume:/var/lib/mysql
  redis:
    image: "redis:alpine"
    networks:
      - varapp
    restart: always
    ports:
      - "6379:6379"
  backend:
    image: varapp-backend
    networks:
      - varapp
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    volumes:
      - ${GEMINI_DB_PATH:-./resources/db}:/db

networks:
  varapp: {}
